### ISSUE TITLE
Documentation on Intended usage?

### ISSUE THREAD

**Issue by thekua** [alphagov/smart-answers#1]
Hi there, 

I've been asked to look at using this project for a rails application. I'm just wondering if this will be offered as a gem? 

If intended for use, it'd be good to add to the readme what steps you need to do to add a new questionnaire. I've guessed the following steps, but not sure:
o New yml file
o New rb file (for custom workflow)
o New routes definition
o New templates 
o Registration in the OpenStruct with panopticon.rake

Anything that I'm missing?

**Comment by chrisroos** [comment]
I'm closing this due to a lack of updates in over three years.
