### ISSUE TITLE
Refactor FLOW_REGISTRY_OPTIONS

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1546]
This constant is used to keep default configuration options for the smart answer registries. The registry instances are cached in class variables and [complain](https://github.com/alphagov/smart-answers/blob/34b2c115c87227ebdd97e1ca27a6d96bcdc60390/lib/smartdown_adapter/registry.rb#L8-L10) if a different instance is requested. We end up [modifying the constant](https://github.com/alphagov/smart-answers/blob/34b2c115c87227ebdd97e1ca27a6d96bcdc60390/test/helpers/test_fixtures_helper.rb#L3-L5) in tests to work around this issue.

This can cause random test failures depending on the test scenario order if not reset to old values in teardown stage correctly.

I suggest encapsulating the constant in a class method eg `FlowRegistry.config` that gets initiated [here](https://github.com/alphagov/smart-answers/blob/34b2c115c87227ebdd97e1ca27a6d96bcdc60390/config/initializers/flow_preview.rb#L4). This would allow stubbing out the test configuration on a per-case basis without worrying of changing the state globally.

We could also encapsulate the stubbing itself in a test helper that would take care of other related things that get cached in class variables (e.g. plugin load paths), which would help with issues like [this](https://github.com/alphagov/smart-answers/commit/34b2c115c87227ebdd97e1ca27a6d96bcdc60390) too.

Other suggestions welcome :)

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/WEGW7pBh/143-refactor-flow-registry-options) (not public).

Closing this issue.
