### ISSUE TITLE
No "Start again" link on *first* question of smart answer

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1591]
This seems to be true for both Ruby/YAML and Smartdown smart answers, e.g.

* http://smart-answers.dev.gov.uk/vat-payment-deadlines/y
* https://www.gov.uk/pay-leave-for-parents/y

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

[Trello card](https://trello.com/c/msKwiDcu/134-no-start-again-link-on-first-question-of-smart-answer).

Closing this issue.
