### ISSUE TITLE
Clicking "Start again" link shows start page with wrong URL path and without related content

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1592]
Steps to reproduce:

* Ensure JavaScript is enabled
* View the start page for the "VAT payment deadlines" smart answer [directly](https://www.gov.uk/vat-payment-deadlines)
* In a new browser tab, click the "Start again" link on [one of the question pages](https://www.gov.uk/vat-payment-deadlines/y/2014-02-28)
* In the latter case, you will see that:
  * the related content on the right-hand side does not appear
  * the URL path is for the first question page (you can see this by refreshing the page)

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/X1WFdk3Q/135-clicking-start-again-link-shows-start-page-with-wrong-url-path-and-without-related-content) (not public).

Closing this issue.
