### ISSUE TITLE
Confusing typo in production logstasher configuration

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1593]
Based on the dictionary and looking at the `logstasher` documentation, it looks as if `supress_app_logs` [in the production configuration](https://github.com/alphagov/smart-answers/blob/master/config/environments/production.rb#L72) should be `suppress_app_logs`. However, looking at the `logstasher` code, it appears as if [the mis-spelt version is also supported](https://github.com/shadabahmed/logstasher/blob/master/lib/logstasher.rb#L104-L107)!

Even though it is supported, I'd suggest that it is confusing for developers reading the code.

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/7BJlhRv0/136-confusing-typo-in-production-logstasher-configuration) (not public).

Closing this issue.
