### ISSUE TITLE
Allow custom error messages per question

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1605]
This issue replaces the [deferred test](https://github.com/alphagov/smart-answers/blob/4270e7b534169b55a6fc3359b6e0fb541f51d3b0/test/unit/flow_test.rb#L209-L212) in `test/unit/flow_test.rb`. I'm about to remove this test which has been deferred for over 3 years and is just cluttering up the test output for no good reason.

**Comment by floehopper** [comment]
I believe that this (or very closely related) behaviour does already exist. See [my comment here](https://github.com/alphagov/smart-answers/commit/d7b66ed91bc0cb5334a0de1884787c61a0d5cc01#commitcomment-11363692) for further info.

**Comment by chrisroos** [comment]
I'm closing this issue as the code does support custom error messages per question.
