### ISSUE TITLE
Failing tests caused by duplicate context names

### ISSUE THREAD

**Issue by chrisroos** [alphagov/smart-answers#1626]
We appear to have a number of failing tests that aren't currently running because their names clash with other tests in the repo. The problem is caused by multiple contexts with the same name, containing tests with the same names.

I've created a script that attempts to give all contexts unique names to reveal these failing tests - https://gist.github.com/chrisroos/e7df2b0ded95a0098f1a

I've not yet attempted to fix any of these failures.

@tadast has previously fixed some similar failing tests in 4dfff6356ee30f6a7907a1998874622fdbf017ef.

**Comment by tadast** [comment]
Your version that runs all tests: 3548 runs, 18021 assertions

Currently on master: 3525 tests, 17897 assertions

**Comment by chrisroos** [comment]
I've just run the [rename-shoulda-contexts.rb] script in my local copy of Smart Answers, ran `rake` and didn't see any test failures. I can only imagine we've gradually fixed these problems while making other changes in the code/tests.

Closing.
