### ISSUE TITLE
Phrase "translations" rendered multiple times

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1628]
There are two things worth investigating.

## Translations invoked prematurely

Looks like some phrases that should only be used in outcome nodes are being "translated" in the questions that lead to that outcome eg if you add a `Rails.logger.warn("[Translating] #{@i18n_prefix}.phrases.#{phrase_key}")` somewhere [here](https://github.com/alphagov/smart-answers/blob/de7619dfd88c8f344c67285f003c0e6f159ec3ec/app/presenters/node_presenter.rb#L35-L40) and visit http://smartanswers.dev.gov.uk/maternity-paternity-calculator/y/maternity/2015-08-11/yes, you will see that [this phrase](https://github.com/alphagov/smart-answers/blob/de7619dfd88c8f344c67285f003c0e6f159ec3ec/lib/smart_answer_flows/shared_logic/maternity-calculator.rb#L21) is rendered there. 
I believe this should not be required

## Translations invoked multiple times

If you visit [any outcome](http://smartanswers.dev.gov.uk/maternity-paternity-calculator/y/maternity/2015-08-11/yes/2015-05-26/yes/yes/2015-04-29/2015-02-28/monthly/4000.0/usual_paydates/last_working_day_of_the_month/1,2,3,4,5) you will see that a lot of phrases are being "translated" multiple times. I'm curious if this can be avoided.

**Comment by chrisroos** [comment]
I don't believe this is a problem now that we've switched away from using the `I18nRenderer`.

The original problem was in `I18nRenderer#translate!` and its call to `I18n.translate!`. The call to `I18nRenderer#state_for_interpolation` in that method resulted in the return value of every method on the `state` object being sent to `I18nRenderer#value_for_interpolation`. If the value sent to `#value_for_interpolation` was a `PhraseList` then we'd call `I18n.translate!` _again_, which would result in another call to `I18nRenderer#state_for_interpolation`. I think this explains both problems listed in this issue, i.e. why we were seeing multiple translations of the same key, and why we were seeing phrases translated even when they weren't required by a given outcome.

Closing.
