### ISSUE TITLE
SimpleCov failed to recognize the test framework and/or suite used

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1669]
I've just noticed the following in the output from a [Jenkins build](https://ci-new.alphagov.co.uk/job/govuk_smart_answers/2439/console).

    SimpleCov failed to recognize the test framework and/or suite used. Please specify manually using SimpleCov.command_name 'Unit Tests'.

I'm in the middle of something else at the moment, but it's probably be worth investigating what this means.

**Comment by chrisroos** [comment]
The Jenkins build linked to in the issue description no longer exists.

I've looked at a [build on Jenkins from today](https://ci.dev.publishing.service.gov.uk/job/govuk_smart_answers/2967/consoleFull) and can't see the error message referenced so I'm going to close this.
