### ISSUE TITLE
Formatting of Taiwan's British Trade & Cultural Office email addresses looks wrong

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1685]
https://www.gov.uk/register-a-birth/y/pitcairn-island/father/no/2015-02-02/another_country/taiwan#go-to-the-british-trade--cultural-office

    Email: <info.taipei@fco.gov.uk Email: Bass.Taipei@fco.gov.uk (consulars enquiries)>

Looking at the Taiwan page on Whitehall, it looks as if this is a data issue:

https://www.gov.uk/government/world/taiwan

**Comment by tadast** [comment]
I've seen similar issues in marriage abroad. Looking at [JSON](https://www.gov.uk/api/world-locations/taiwan/organisations) it seems like we may be assuming too much about the values in that field

**Comment by chrisroos** [comment]
I've asked in Slack who we should report this data issue to.

Closing as this isn't an issue with Smart Answers.

**Comment by chrisroos** [comment]
I've now opened a Zendesk ticket to report the data problem - https://govuk.zendesk.com/tickets/1198120
