### ISSUE TITLE
Investigate organisations API usage

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1708]
Investigate if it would be beneficial to use the API more extensively for things like:

- [this](https://github.com/alphagov/smart-answers/blob/faff424d310ba8fdad14de1127cdf6059848163f/lib/smart_answer_flows/locales/en/marriage-abroad.yml#L1463-L1586), finding out if the country has an embassy/high comission/consulate and where in the country it is
- finding out if countries have [no consular facilities](https://github.com/alphagov/smart-answers/blob/c53867b2337f01319333994ae305ee33c5df4e25/lib/smart_answer/calculators/marriage_abroad_data_query.rb#L17-L19)

The risk would be content changing as the API is being updated. Which should not be a problem as long as the code is robust and makes sure it handles expected changes correctly.

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/EwuhT4lk/144-investigate-using-the-organisations-api-in-marriage-abroad) (not public).

Closing this issue.
