### ISSUE TITLE
[BUG] Handling 29th of Feb in calculate-your-holiday-entitlement

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1828]
path to reproduce: /calculate-your-holiday-entitlement/y/days-worked-per-week/leaving/2015-05-01/2016-02-29/1

It fails with an unhelpful error message `undefined local variable or method `holiday_entitlement_days'`. This is because the block calculating the value raises an error, but it disappears (we should look at that separately).

The real issue is handling 29th Feb, which only exists in leap years. [This method](https://github.com/alphagov/smart-answers/blob/master/lib/smart_answer/calculators/holiday_entitlement.rb#L135-L137) fails
 as it's not taking into consideration leap year dates (funnily enough that's the main reason it was written).

I'm leaving it here for now as it's an edge case and I have other time-sensitive things at the moment.

**Comment by floehopper** [comment]
It happened again today: https://errbit.publishing.service.gov.uk/apps/533c35ae0da1159384044f5f/problems/560ef3cc65786306396e1000

Since it keeps happening, it would be good to fix this soon.

I'd hope that using the `YearRange` class might make it easier to fix it.

**Comment by chrisroos** [comment]
This has happened again today - https://errbit.publishing.service.gov.uk/apps/533c35ae0da1159384044f5f/problems/5632289c657863063bd71d00

It's worth noting that the error is now "ArgumentError: Invalid date" now that we're no longer rescuing `ArgumentError`s raised in the `next_node` blocks (see PR #2032 for more).

**Comment by chrisroos** [comment]
I think @erik-eide has fixed this problem in PR #2041.

**Comment by erik-eide** [comment]
Closing this, seems to have been resolved with #2041 with the failing [URL](https://www.gov.uk/calculate-your-holiday-entitlement/y/days-worked-per-week/leaving/2015-05-01/2016-02-29/1) now ok
