### ISSUE TITLE
Potential Marriage abroad improvements

### ISSUE THREAD

**Issue by tadast** [alphagov/smart-answers#1885]
Reviewing https://github.com/alphagov/smart-answers/pull/1882 I've noticed some potential improvements that could be done to the marriage-abroad smartanswer. In no particular order:

  - [x] Portugal same sex marriage title says "Same-sex in Protugal"
  - [x] Remove the TODO comment, it is ok! https://github.com/alphagov/smart-answers/commit/e6a965a49e710a9f192a693d977360c88914ef3a
  - [ ] consider moving Italy (also Japan, Germany?) out of the consular CNi outcome https://github.com/alphagov/smart-answers/commit/b095fbdebb4b6a4cbbd57db6905512d1fa526781
  - [ ] Japan-local does not use standard appointments booking link partial, standardise https://github.com/alphagov/smart-answers/commit/93a86f8a4ef0e3ab245433a160a80e9df909fdc3
  - [ ] consider moving Zimbabwe out of the commonwealth outcome

The last few might not be very good improvements, it needs more investigation/spiking.

**Comment by chrisroos** [comment]
I'm closing this issue (and not creating an equivalent Trello card) as I'm not sure how useful this would be for a developer new to the project.
