### ISSUE TITLE
Investigate intermittent test failure - possibly related to recent content_id changes

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#1976]
I've seen this test failure at least once on our Jenkins govuk_smartanswers_branches build e.g. see the bottom of the console log for [this build](https://ci-new.alphagov.co.uk/job/govuk_smartanswers_branches/3018/console), and several times when running the tests via `rake` on my local machine.

    1) Error:
    SmartAnswer::FlowContentItemTest#test_#payload_returns_a_valid_content-item:
    GovukContentSchemaTestHelpers::ImproperlyConfiguredError: Dependency govuk-content-schemas cannot be found at: /Users/jamesmead/Code/alphagov/govuk-content-schemas. Clone it to that directory, or set GOVUK_CONTENT_SCHEMAS_PATH (see README.md for details).
      test/unit/flow_content_item_test.rb:13:in `block in <class:FlowContentItemTest>'

Note that @chrisroos, @tadast & I are running the smart-answers app outside the gov.uk VM, because it's a relatively simple app with not many dependencies in case that's significant.

**Comment by floehopper** [comment]
@tijmenb: Do you have any ideas why this might be happening? Thanks.

**Comment by tijmenb** [comment]
As for the test failure on your machine: the schema-tests you need to have checked out the `govuk-content-schemas` repo on your system (in this case `/Users/jamesmead/Code/alphagov/..`). The error message is trying to tell that, but obviously isn't clear enough. If you have suggestions on how to reword that I'll update it.

The branch failure is weirder: was that branch up to date with master?

**Comment by floehopper** [comment]
@tijmenb: Sorry for the slow response. The error message is clear enough - I was just confused by why it suddenly started happening. Thanks for explaining.

I'm still slightly confused as to why it seems to have only been happening intermittently - and possibly not at all more recently despite me only having just checked out the `govuk-content-schemas` repo.

Also weird that it was happening on Jenkins, but again doesn't seem to be happening any more...

Anyway, I think I'll close this issue for now and we can re-open it if it happens again.
