### ISSUE TITLE
Intermittent `Capybara::ElementNotFound` test failure in ReportAProblemTest

### ISSUE THREAD

**Issue by floehopper** [alphagov/smart-answers#2092]
This test is passing locally, so I can only assume it's another race condition in a JS-enabled integration test.

See this build for an example of the failure: https://ci.dev.publishing.service.gov.uk/job/govuk_smartanswers_branches/3338/console

```
ReportAProblemTest#test_: with javascript smart-answer question should show report-a-problem. :
Capybara::ElementNotFound: Unable to find field "Name:"
    test/integration/engine/report_a_problem_test.rb:34:in `block (4 levels) in <class:ReportAProblemTest>'
```

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/X9c5x8g7/141-intermittent-capybara-elementnotfound-test-failure-in-reportaproblemtest) (not public).

Closing this issue.
