### ISSUE TITLE
Fix Smart Answer withdrawal process

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/smart-answers#2356]
As a user
I want withdrawn smart answers to redirect me
So that I can find an alternative path for my need

As an Information Architect
I want withdrawn smart answers to be removed from Publishing API
So that I don't accidentally tag them to browse pages

The current documentation and process for withdrawing Smart Answers is incomplete. It leaves artefacts in Panopticon and Content Items in the Publishing API and Content Store. If a Smart Answer is withdrawn, the following should happen:

1. Withdraw the Artefact in Panopticon, preferably using the API
2. Publish a redirect item to the Publishing API in place of the Smart Answer
3. The Smart Answer should no longer be pushed to the Publishing API on deploy

**Comment by chrisroos** [comment]
@boffbowsh: Was this prompted by your experience removing apply-tier-4-visa in PR #2339? Assuming it was:

1. How did you remove the artefact in Panopticon? If you used the API can you point us to how you did it?

2. How did you publish a redirect item to the Publishing API?

3. Did you have do anything more than simply delete the apply-tier-4-visa Smart Answer from the project?

**Comment by boffbowsh** [comment]
That's correct. There currently isn't an API in Panopticon for withdrawing content, but it shouldn't be too difficult to create one. A redirect item has to follow [this schema](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/redirect/publisher_v2/schema.json), and should be an unpreserved (`"segments_mode": "ignore"`) prefix redirect to the new location in order to catch people who've bookmarked partially complete Smart Answers. I didn't do anything special to remove that Smart Answer, other than the above.

**Comment by floehopper** [comment]
@erikse, @ikennaokpala, @pmanrubia, @chrisroos: Should we capture this in a Trello card to avoid it getting forgotten? If so which board should it go on?

**Comment by ikennaokpala** [comment]
@floehopper Maybe be opened in the [Smart Answer Task board](https://trello.com/b/7HgyU4hy/smart-answers-tasks)..

**Comment by floehopper** [comment]
@ikennaokpala: Oh. I already saw your comment and created [this card][1].

[1]: https://trello.com/c/leHXvtqN

**Comment by floehopper** [comment]
I'm going to close this issue now that it's been captured in [this Trello card][1].

**Comment by chrisroos** [comment]
Thanks for your reply, @boffbowsh.

I'm afraid I don't know anything about the Publishing API so I'm struggling to follow your instructions for creating a redirect: 

> A redirect item has to follow [this schema](https://github.com/alphagov/govuk-content-schemas/blob/master/formats/redirect/publisher_v2/schema.json), and should be an unpreserved `("segments_mode": "ignore")` prefix redirect to the new location in order to catch people who've bookmarked partially complete Smart Answers.

Can you point me at some documentation or some other projects/code that publish redirects, please?

**Comment by boffbowsh** [comment]
Whitehall has a [Redirect content item presenter](https://github.com/alphagov/whitehall/blob/master/app/presenters/publishing_api_presenters/redirect.rb) that you should be able to use as an example.

**Comment by chrisroos** [comment]
Thanks, @boffbowsh.
