### ISSUE TITLE
Could the Meursing code checker link to the trade tariff

### ISSUE THREAD

**Issue by matthewford** [alphagov/smart-answers#2492]
Use these four digits together with the ten-digit commodity code from [Trade Tariff](https://www.gov.uk/trade-tariff).

**Comment by pmanrubia** [comment]
Hi @matthewford, Thank you for your suggestion. 
We will keep you posted about its resolution.

In the meantime, I would appreciate if you could provide us the URL with the copy you would like to update.

**Comment by matthewford** [comment]
So that the moment, it just says "Trade Tariff", if this could link to: https://www.gov.uk/trade-tariff 

That would be great thanks.

**Comment by selfthinker** [comment]
This has now been changed in the code and will probably get released within the next 2 days. I will let you know when it is live.

**Comment by selfthinker** [comment]
This has now been released.
