### ISSUE TITLE
Javascript error being reported on Smart Answer pages

### ISSUE THREAD

**Issue by fofr** [alphagov/smart-answers#2858]
```TypeError: null is not an object (evaluating 'elt.parentNode')```
These errors occur only on iOS Safari (version 600.1.4)

Top offending pages:
```
/state-pension-age
/pay-leave-for-parents
/calculate-your-child-maintenance
/calculate-your-holiday-entitlement
```

We're seeing about 28,000 errors reported in GA each day.

**Comment by selfthinker** [comment]
This might get fixed with removing the AJAX which we planned to do since ages. See https://trello.com/c/j7tWmjbO/324-remove-ajax-from-smart-answers and https://github.com/alphagov/smart-answers/tree/remove-ajax (which is currently blocked and de-prioritised).

**Comment by nickcolley** [comment]
This is not breaking functionality that I can see.

I've reproduced this on iOS via the following:
- Use browserstack with iOS 6 device
- Navigate to http://www.gov.uk/state-pension-age
- The pages are doing full reloads rather than the Ajax + Pushstate behaviour

**Comment by benthorner** [comment]
This issue is very old, and seems redundant now (the pages mentioned here are now rendered by [frontend](https://github.com/alphagov/frontend/issues)). I'm going to close this, but happy to reopen if someone comments there's still an issue.
