### ISSUE TITLE
Unwanted zoom behaviour on inputs iOS Safari 

### ISSUE THREAD

**Issue by nickcolley** [alphagov/smart-answers#2859]
https://youtu.be/5TPmncmZwXI

When focusing elements on iOS Safari, it will zoom the viewport.

If the inputs text size is not too small (like in GOV.UK Elements) this behaviour does not happen.

Recommend we update these inputs to the new patterns.

**Comment by selfthinker** [comment]
What do you mean by "if the inputs text size is not too small"? Why would this behaviour be different in GOV.UK Elements?
Does this only happen with selects or also with other inputs?

**Comment by selfthinker** [comment]
If I understand it correctly, it also happens with Elements, although I found much less examples.
This would then largely be fixed when we move Smart Answers to use Elements (which is currently blocked by content work).

**Comment by nickcolley** [comment]
If the `font-size` is lower that 16px (the default in many browsers) the interface will zoom.

Here's a good example https://uxcellence.com/2014/01/15/quick-fix-increase-font-size-to-16px-to-fix-input-zoom

**Comment by nickcolley** [comment]
Closing old issues.
