### ISSUE TITLE
Pending work on PR to retire a Smart Answer

### ISSUE THREAD

**Issue by pmanrubia** [alphagov/smart-answers#2995]
#2994 has been merged because of an urgent deployment. The code is currently working and the tests passing.

We need to continue working on the PR code, so I have created this issue to track this work.

- [x] Write documentation about what are the steps to retire a smart-answer
- [x] Remove [direct call to GDS::Router][1] once Content Store is able to pass the segment configuration to `router-api`
- [x] Remove references to `content-store` and update them with `publishing-api`
- [x] [Decompose long method into smaller chunks][2] so it is easier to understand what the method is doing
- [x] Some comments already left in #2994
- [x] As per [today's deployment][3] the rake task to create the redirect is failing to set the segment in staging and production. It was needed to connect to the Rails console in production of `router-api` and set the segment path manually.
- [x] Add task to remove the URL from Search using [Rummager][4]
- [x] Add consolidated rake task for retiring a smart answer

[1]: https://github.com/alphagov/smart-answers/pull/2994/commits/bdf834aba55e681e0a5b8e2db4715dc9accc1fc9#diff-8cef3e0c497f0b3bd493ed82777c86d2R35
[2]: https://github.com/alphagov/smart-answers/pull/2994/commits/bdf834aba55e681e0a5b8e2db4715dc9accc1fc9#diff-8cef3e0c497f0b3bd493ed82777c86d2R22
[3]: https://deploy.staging.publishing.service.gov.uk/job/run-rake-task/942/
[4]: https://github.com/alphagov/rummager

**Comment by ikennaokpala** [comment]
Closing this issue as #3001 resolves the issues raised here..
