### ISSUE TITLE
The instructions for getting started don't work anymore?

### ISSUE THREAD

**Issue by vickytnz** [alphagov/smart-answers#3136]
I can use the other examples of the repo, but when I start creating one from the instructions
https://github.com/alphagov/smart-answers/blob/master/doc/creating-a-new-smart-answer.md
but as soon as I get to the 

> "Assuming you're still running rails server, visit http://localhost:3000/example-smart-answer and you should see the empty landing page of our new Smart Answer."

I just get errors
```
NoMethodError at /example-smart-answer
undefined method `dig' for nil:NilClass
```
![image](https://user-images.githubusercontent.com/1223264/28090246-9851d89c-6683-11e7-9bc1-d70df21f8e3a.png)

![image](https://user-images.githubusercontent.com/1223264/28090335-dcfd3752-6683-11e7-9612-31c269970f4e.png)

has something changed?

**Comment by chao-xian** [comment]
Hi @vickytnz thanks for flagging this. There is an assumption that the SmartAnswer being created also exists in the GOV.UK Content Store, but the example used to cope with that not being the case. It appears that the navigation, which is undergoing AB testing, now always assumes that the Smart Answer is in the Content Store. 

I'm not certain that we will ever likely fix this as Smart Answers is treated as a BAU app and we are not creating new "smart answers" to add in. We are more active in retiring or moving them from out of the app. But I'll check (Cc @pmanrubia)

Also out of curiosity what are your plans with Smart Answers? It may not be the most useful for your purposes. If you want to give me a shout I'm also on the x-gov slack.

**Comment by ikennaokpala** [comment]
@vickytnz Thanks for reporting this issue.. This issue has now been resolved.. Kindly pull latest changes on master.
