### ISSUE TITLE
Use text input date pattern for known dates (eg date of birth)

### ISSUE THREAD

**Issue by fofr** [alphagov/smart-answers#3240]
Our recommended pattern for inputting dates of birth is using text inputs:
http://govuk-elements.herokuapp.com/form-elements/example-date/

![screen shot 2017-10-25 at 15 19 38](https://user-images.githubusercontent.com/319055/32003751-f0780af2-b997-11e7-9a41-da8b6965631e.png)

Users struggle with the existing drop downs:
https://www.gov.uk/state-pension-age/y/age
![screen shot 2017-10-25 at 15 20 17](https://user-images.githubusercontent.com/319055/32003797-0e9c4f98-b998-11e7-8b2a-bac79ddff593.png)

Also no one is alive who was born in 1899 or before:
https://en.wikipedia.org/wiki/List_of_the_verified_oldest_people

**Comment by tijmenb** [comment]
Now tracked here: https://trello.com/c/OkS6608Z/49-use-input-components-in-smart-answers

We've had a bunch of discussion on Slack about the date input. We really should be using the date component here, not the select box.
