### ISSUE TITLE
Graphviz representation of a smart answer flow returns 503

### ISSUE THREAD

**Issue by jennyd** [alphagov/smart-answers#3707]
The interactive visualisations are working fine, but the Graphviz format (documented [here](https://github.com/alphagov/smart-answers/blob/f1176f991ee188294184ee9929dea5a5c93860bc/doc/debugging/visualising-flows.md)) returns 503 on all the ones I've tried.

I also can't find any tests for `GraphvizPresenter` to see what the expected output should look like.

**Comment by kevindew** [comment]
Hi @jennyd - sorry you didn't hear back from anyone for a year and a half (I'm wondering if this was before or after you left GDS). The good news is this now works again and has a test.

**Comment by jennyd** [comment]
Thanks @kevindew! It was after I left GDS - I can't remember exactly how I came across these visualisations being broken, but glad they're working now 🎉  They're a useful example to be able to point to of making a service more transparent. We should do something like this for forms on [MOJ's Form Builder platform](https://github.com/ministryofjustice/form-builder)...

**Comment by kevindew** [comment]
Oh cool project. I'm going to have a nosey.
