### ISSUE TITLE
Running "bundle install" is failing on Windows

### ISSUE THREAD

**Issue by jamiehumphries** [alphagov/smart-answers#3916]
I am trying to get the project running on a Windows machine.

I have installed Ruby 2.6.1 (as per [`.ruby-version`](https://github.com/alphagov/smart-answers/blob/master/.ruby-version)) and run `gem install bundler`, but then when I run `bundle install` I get an error when resolving dependencies.

```
C:\Work\smart-answers (master)
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]

C:\Work\spl\smart-answers (master)
$ gem install bundler
Fetching bundler-2.0.1.gem
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
Done installing documentation for bundler after 17 seconds
1 gem installed

C:\Work\spl\smart-answers (master)
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "ruby ":
  In Gemfile:
    ruby  (~> 2.6.1.0)

    slimmer (~> 13.0.0) was resolved to 13.0.0, which depends on
      rest-client was resolved to 2.0.2, which depends on
        http-cookie (>= 1.0.2, < 2.0) was resolved to 1.0.3, which depends on
          domain_name (~> 0.5) was resolved to 0.5.20180417, which depends on
            unf (>= 0.0.5, < 1.0.0) was resolved to 0.1.4, which depends on
              unf_ext was resolved to 0.0.7.5, which depends on
                ruby  (< 2.6) x64-mingw32

Could not find gem 'ruby  (< 2.6)', which is required by gem 'nokogiri', in any
of the relevant sources:
  the local ruby installation
```
The error suggests that the problem is that the Ruby version needs to be less than 2.6, however I have also tried the install using version 2.5.3 and even after downgrading the `.ruby-version` file, the install fails again, though with different gems in the error message.

Any help with this would be most appreciated, as it is currently preventing me from running the code.

**Comment by asadalien** [comment]
this is an issue in windows i am also facing right now

**Comment by maxgds** [comment]
Sorry but we are not set up to provide user support for external people and internally we wouldn't expect to be running smart answers code in a windows environment, so I'm going to close this issue as a won't fix.
