### ISSUE TITLE
Implicit defaults for rendering formats in node .erb templates

### ISSUE THREAD

**Issue by theseanything** [alphagov/smart-answers#4510]
A [review comment](https://github.com/alphagov/smart-answers/pull/4502#discussion_r420169537) in PR #4502 discussed that different default rendering behaviours for the `render_content_for` method with node templates may results in confusion as to what format content should be written in. 

It was suggested that we could add multiple methods  e.g:
- `govspeak_content_for`
- `text_content_for`
- `html_content_for`

to be explicit in the type of content required.

**Comment by theseanything** [comment]
This implicit behaviour of different rendering default for different named `(render_)content_for` blocks has existed since moving to erb templates. Not sure if people have previously found it confusing. The behaviour also documented [here](https://github.com/alphagov/smart-answers/tree/master/doc/smart-answers/erb-templates).

Some named content must be a specific format (e.g. `:title` have to always be format `:text`) A possible issue with explicitly stating the format is that it adds a requirement for the person writing erb templates to know what the required format is for particular named section.

I feel like there's a larger issue around trying to put multiple formats in erb template and whether thats the most appropriate way of specifying content.

**Comment by kevindew** [comment]
@theseanything I've opened up a draft PR to propose an approach: https://github.com/alphagov/smart-answers/pull/4527

Revising on my earlier suggestion I felt we didn't need the word content and could go with rather succinct `text_for`, `html_for` and `govspeak_for` methods, which also seems to make the language more natural.

I don't think it covers all the concerns you've had though, but hope you think of it as an improvement.

**Comment by theseanything** [comment]
This can be closed - we settled on `text_for`, `html_for` and `govspeak_for` and it's been working fine.
