### ISSUE TITLE
Visual issue on "business-coronavirus-support-finder"

### ISSUE THREAD

**Issue by chris-gds** [alphagov/smart-answers#5434]
## Problem 

There is a line-height visual issue found on this page.
https://www.gov.uk/business-coronavirus-support-finder

### (Problem: Left, Ideal Solution: Right)

![image](https://user-images.githubusercontent.com/71266765/121713987-5520f480-cad5-11eb-9722-7f1d51a861bf.png)

## Investigation

The rendering element appears here:
https://github.com/alphagov/smart-answers/blob/cc59055d1876d8dd4526050515a46cc0c82cf880/app/views/smart_answers/landing.html.erb#L23

This issue appears to come from using the the deprecated [`govuk_template`](https://github.com/alphagov/govuk_template). Should relevant files be removed this resolves the issue. However the knock on impact would need review.

[`https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_basic.scss`](https://github.com/alphagov/govuk_template/blob/134e8b910c5175d5f94b1f5c48fdc342bb5065c2/source/assets/stylesheets/_basic.scss#L66)

## Anything else?
Initially it was thought this was related a11y team work, this doesn't appear to be the case. [A temporary fix was raised here as a PR](
https://github.com/alphagov/smart-answers/pull/5432) however this needs further investigation.

**Comment by theseanything** [comment]
@chris-gds did this get resolved?

**Comment by alex-ju** [comment]
Fixed in https://github.com/alphagov/govuk_publishing_components/pull/2273
