### ISSUE TITLE
Components have no tests

### ISSUE THREAD

**Issue by andysellick** [alphagov/smart-answers#5695]
This repo contains [four components](https://github.com/alphagov/smart-answers/tree/main/app/views/components) that have no associated tests, as required by our [component conventions](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/component_conventions.md#tests).

[This PR](https://github.com/alphagov/smart-answers/pull/5694) adds the necessary code to allow component `_test.rb` files to be added. We just need to write some.

**Comment by MartinJJones** [comment]
All components in Smart Answers now have tests.

The required changes have been made in the PR's below:

Remove user intent banner component - https://github.com/alphagov/smart-answers/pull/6077
Add tests for the result section and item components - https://github.com/alphagov/smart-answers/pull/6093
Add test for the result card component - https://github.com/alphagov/smart-answers/pull/6095
