### ISSUE TITLE
Update `govuk-` classes in `result-item.scss`

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/smart-answers#5965]
## What
Replace the `.govuk-` classes in the styling of the result-item component to use BEM specifically for the component
https://github.com/alphagov/smart-answers/blob/main/app/assets/stylesheets/components/_result-item.scss

## Why
To adhere to the Single Responsibility Principle in the CSS Style guide:
https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/coding-standards/css.md#single-responsibility-principle

>Each class has a single purpose, so you can be sure when making a change to a class - it will only affect the element that class is applied to.

> Also when deprecating classes, all of the CSS for this class can be removed without affecting another component that had reused this css.

>Why? 
To ensure that styles can safely be added or removed without fear of breaking other components.

**Comment by maxgds** [comment]
I think you want additional classes, replacements. You don't really want to re-implement what the likes of govuk-heading-s does, but equally you don't want to hang your margins off it.

**Comment by jon-kirwan** [comment]
Can we replace these classes with Design System utility classes?

There would be one issue in that the DS classes are all responsive, whereas in at least in one case here, the class has used a static spacing function `.govuk-body { margin-bottom: govuk-spacing(6); }` so the closest would see a 10px difference between mobile and desktop. For example -

```
<p class="govuk-body govuk-!-margin-bottom-6"><%= topic %></p>
```

```
@media (min-width: 40.0625em)
.govuk-\!-margin-bottom-6 {
    margin-bottom: 30px !important;
}

.govuk-\!-margin-bottom-6 {
    margin-bottom: 20px !important;
}
```
