### ISSUE TITLE
Duplication of value presentation logic

### ISSUE THREAD

**Issue by heathd** [alphagov/smart-answers#971]
(Note: moved this out of the README)

The way that values are presented is badly factored. Values need to be
formatted for presentation in two places:

1. when displaying a collapsed question;
2. when interpolating values into question text.

Values can come from two places:

1. directly from a response (`save_input_as`);
2. via a calculation.

To correctly present a multiple-choice response value, you need to
know the question where it was posed. Other question types may also
determine formatting/presentation rules on a per-question basis so it
makes sense that it's determined at that point.

However, at present we don't remember which question gave rise to a
saved input, so this formatting is impossible.

There are two (duplicated) implementations of formatting response
labels:

1. the node presenters, e.g. `DateQuestionPresenter#response_label`
2. `NodePresenter#value_for_interpolation`

This is duplication and should be refactored out.

For now I don't think we ever need to interpolate in the responses of
multiple choice questions, so I think we could solve this issue (ie implement a single value presentation function) by:

1. determining formatting from the type of the value
2. adding a money type

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/cirj8MK6/145-consistently-format-values-for-display-in-questions-and-outcomes) (not public).

Closing this issue.
