### ISSUE TITLE
AgeRelatedAllowanceChooser could be generalised

### ISSUE THREAD

**Issue by heathd** [alphagov/smart-answers#972]
(Note: pulled out of README)

The `AgeRelatedAllowanceChooser` has been created to return the
age-related personal allowance to assist with the calculation of
married couple's allowance. However, the reduction of allowances that
takes place in `MarriedCoupleAllowanceCalculator` applies to other tax
calculations, as your personal allowance depends on both your age and
income. So the `AgeRelatedAllowanceChooser` could be changed to a
`PersonalAllowanceCalculator` and extended such that it takes all those
factors into account and can be used across the system to calculate
someone's personal allowance depending on their age, income, and if
required, other factors:

[http://www.hmrc.gov.uk/incometax/personal-allow.htm]

**Comment by chrisroos** [comment]
I've moved this to Trello in an attempt to end up with a single place containing Smart Answers stories/tasks/bugs.

See the [Trello card](https://trello.com/c/XLE6L7s8/142-agerelatedallowancechooser-could-be-generalised) (not public).

Closing this issue.
